---
# tasks file for virtualenvwrapper
- name: install virtualenvwrapper
  pip: >
    name=virtualenvwrapper
    version={{ virtualenvwrapper_version }}
    state=present
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_installation

- name: set workon home (home for virtuaenvs)
  lineinfile: >
    dest={{ virtualenvwrapper_shell_rc_file }}
    regexp='export WORKON_HOME'
    line='export WORKON_HOME={{ virtualenvwrapper_venvs_home }}'
    state=present
    backup=yes
    create=yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_configuration

- name: set project home
  lineinfile: >
    dest={{ virtualenvwrapper_shell_rc_file }}
    regexp='export PROJECT_HOME'
    line='export PROJECT_HOME={{ virtualenvwrapper_venvs_project }}'
    state=present
    backup=yes
    create=yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_configuration

- name: set virtualenvwrapper python path (if variable is set)
  lineinfile: >
    dest={{ virtualenvwrapper_shell_rc_file }}
    regexp='export VIRTUALENVWRAPPER_PYTHON'
    line='export VIRTUALENVWRAPPER_PYTHON={{ virtualenvwrapper_venvs_python }}'
    state=present
    backup=yes
    create=yes
  when: virtualenvwrapper_override_python
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_configuration

- name: load virtualenvwrapper script
  lineinfile: >
    dest={{ virtualenvwrapper_shell_rc_file }}
    regexp='source `which virtualenvwrapper.sh`'
    line='source `which virtualenvwrapper.sh`'
    state=present
    backup=yes
    create=yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_configuration

